import {test,expect} from '@playwright/test';
const flux='@cf/black-forest-labs/flux-1-schnell',sdxl='@cf/stabilityai/stable-diffusion-xl-base-1.0';
test('Guided proposals choose capable models explicitly and preserve manual settings across modes',async({page})=>{
  test.skip(!process.env.PLAYWRIGHT_BASE_URL,'Production provider availability requires Pages.');
  await page.route('**/api/generate',route=>route.fulfill({json:{available:true,message:'Test fixture provider availability.'}}));
  await page.goto('/image/');
  await expect(page.getByRole('combobox',{name:'Model',exact:true})).toHaveCount(0);
  await expect(page.getByRole('combobox',{name:'Quality',exact:true})).toHaveCount(0);
  await page.getByLabel('What do you want to create?').fill('A coffee campaign');
  await page.getByRole('combobox',{name:'Desired output format',exact:true}).selectOption('9:16');
  await page.getByRole('combobox',{name:'Visual style',exact:true}).selectOption('Cinematic');
  await page.getByRole('button',{name:'Recommend prompt & settings'}).click();
  await expect(page.getByRole('region',{name:'Suggested prompt and settings'})).toContainText('SDXL can generate your 9:16 format natively');
  await expect(page.getByLabel('Your prompt')).toHaveValue('');
  await expect(page.getByText('Sample Studio (sample)',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Apply recommendation'}).click();
  await expect(page.getByText('Stable Diffusion XL (Cloudflare)',{exact:true})).toBeVisible();
  await expect(page.getByLabel('Your prompt')).toHaveValue(/cinematic color/);
  await page.getByRole('button',{name:'Adjust in Advanced Mode'}).click();
  await expect(page.getByRole('combobox',{name:'Model',exact:true})).toHaveValue(sdxl);
  await expect(page.getByRole('combobox',{name:'Aspect ratio',exact:true})).toHaveValue('9:16');
  await page.getByRole('combobox',{name:'Quality',exact:true}).selectOption('high');await page.getByLabel('Your prompt').fill('Keep my precise manual wording');
  await page.getByRole('button',{name:'Guided',exact:true}).click();
  await page.getByRole('combobox',{name:'Desired output format',exact:true}).selectOption('native');
  await expect(page.getByText('Stable Diffusion XL (Cloudflare)',{exact:true})).toBeVisible();
  await expect(page.getByLabel('Your prompt')).toHaveValue('Keep my precise manual wording');
  await page.getByRole('button',{name:'Advanced',exact:true}).click();await expect(page.getByRole('combobox',{name:'Quality',exact:true})).toHaveValue('high');
  await page.getByRole('button',{name:'Guided',exact:true}).click();await page.getByRole('button',{name:'Recommend prompt & settings'}).click();
  await expect(page.getByRole('region',{name:'Suggested prompt and settings'})).toContainText('FLUX fits a flexible-format idea');
  await page.getByRole('button',{name:'Apply recommendation'}).click();
  await expect(page.getByLabel('FLUX output format')).toContainText('Model default · 1:1');
  await expect(page.getByLabel('FLUX output format')).toContainText('Use SDXL for portrait');
  await page.screenshot({path:'test-results/guided-image.png',fullPage:true});
  await page.getByRole('button',{name:'Advanced',exact:true}).click();await expect(page.getByRole('combobox',{name:'Model',exact:true})).toHaveValue(flux);
  await expect(page.getByRole('combobox',{name:'Aspect ratio',exact:true})).toBeDisabled();
});
