'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {readLibrary,removeItem} from '../lib/library';
import {modelName} from '../lib/creation';
import {sampleURL,downloadSample} from '../lib/generation-provider';
import Icon from './Icons';

export default function AssetLibrary(){
  const [library,setLibrary]=useState({assets:[],recipes:[]});const [ready,setReady]=useState(false);
  const [error,setError]=useState('');const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const [deleting,setDeleting]=useState(null);
  useEffect(()=>{function load(){try{setLibrary(readLibrary(localStorage));setError('');}catch{setError('Local library could not be read. Existing data has been preserved.');}setReady(true);}load();window.addEventListener('storage',load);return()=>window.removeEventListener('storage',load);},[]);
  function remove(collection,id){try{setLibrary(removeItem(localStorage,collection,id));setDeleting(null);setError('');}catch(e){setError(e.message);}}
  const recipes=filter==='recipes';
  const items=(recipes?library.recipes:library.assets).filter(item=>(recipes||filter==='all'||item.kind===filter)&&`${item.name||item.title} ${(item.draft||item.recipe).prompt}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="page assets-page"><div className="page-heading"><div><p className="eyebrow">YOUR CREATIVE LIBRARY</p><h1>Assets<span className="count">{library.assets.length}</span></h1><p>Sample outputs and reusable recipes, saved on this device.</p></div><Link href="/image/" className="button primary">Create a sample <Icon name="arrow" size={17}/></Link></div>{error&&<p className="notice" role="alert">{error}</p>}
    <div className="library-toolbar"><div className="filter-group" aria-label="Library filters">{[['all','All assets'],['image','Images'],['video','Video storyboards'],['recipes','Recipes']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}{id==='recipes'?` (${library.recipes.length})`:''}</button>)}</div><label className="library-search">Search library<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search title or prompt"/></label></div>
    {!ready?<div className="loading-state" role="status">Loading your local library…</div>:items.length?<div className="asset-grid">{items.map(item=>{const d=item.draft||item.recipe;const collection=recipes?'recipes':'assets';return <article className="asset-card" key={item.id}>{!recipes&&<Link href={`/${item.kind}/?asset=${item.id}`} className="asset-preview"><img src={sampleURL(item)} alt={`Saved sample ${item.kind==='video'?'storyboard':'image'}: ${item.title}`}/><span className="media-badge">Sample · not AI-generated</span></Link>}<div className="asset-card-body"><p className="eyebrow">{recipes?`${d.kind} recipe`:item.kind==='video'?'Video storyboard · SVG':'Image · SVG'}</p><h2>{item.name||item.title}</h2><time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleString()}</time><p>{modelName(d.model)} · {d.aspectRatio} · {d.quality} · batch {d.batchSize}{d.kind==='video'?` · ${d.duration}s`:''}</p><div className="action-row"><Link className="button secondary compact" href={`/${d.kind}/?${recipes?'recipe':'asset'}=${item.id}`}>{recipes?'Apply recipe':'Open & reuse recipe'}</Link>{!recipes&&<button className="text-button" onClick={async()=>{setError('');try{await downloadSample(item);}catch(e){setError(e.message||'Download failed. Try again.');}}}>Download</button>}</div>{deleting===item.id?<div className="delete-confirm"><p>Remove from this device? Download first to keep a copy.</p><button className="text-button" onClick={()=>remove(collection,item.id)}>Confirm removal</button><button className="text-button" onClick={()=>setDeleting(null)}>Keep</button></div>:<button className="text-button remove-button" onClick={()=>setDeleting(item.id)}>Remove</button>}</div></article>;})}</div>:<section className="library-empty"><div className="empty-stack"><div/><div/><span><Icon name="assets" size={38}/></span></div><h2>{search?'No matching items.':recipes?'Keep the settings that work.':'Your next idea belongs here.'}</h2><p>{search?'Try a different search or filter.':recipes?'Save a named recipe from any sample result, then reapply it here.':'Create a sample, then choose Save to Assets to keep it after refresh.'}</p><div className="action-row"><Link className="button primary" href="/image/">Open Image Studio <Icon name="arrow" size={17}/></Link><Link className="button secondary" href="/video/">Plan a video</Link></div></section>}
    <p className="library-note">Stored in this browser only. Clearing browser data removes your library. Download important samples. Video entries are storyboards, not playable videos.</p></div>;
}
